#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    iFLeft,         sensorReflection)
#pragma config(Sensor, in2,    iFRight,        sensorReflection)
#pragma config(Sensor, in3,    iRight,         sensorReflection)
#pragma config(Sensor, in4,    iBack,          sensorReflection)
#pragma config(Sensor, in5,    iLeft,          sensorReflection)
#pragma config(Sensor, dgtl1,  button1,        sensorTouch)
#pragma config(Sensor, dgtl2,  button2,        sensorTouch)
#pragma config(Sensor, dgtl3,  sonar,          sensorSONAR_cm)
#pragma config(Sensor, dgtl6,  ir,             sensorDigitalOut)
#pragma config(Sensor, I2C_1,  linI2C,         sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           right,         tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           left,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           linear,        tmotorVex393_MC29, openLoop, encoderPort, I2C_1)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int vFLeft;
int vFRight;
int vLeft;
int vRight;
int vBack;

bool button1p;
bool button2p;

enum control{Forward, Left, Right};
enum control direction;

enum orientation {Down, Up};
enum orientation linearO;

int distanceConnect = 6;

int minLevel = 350;

int mstop = 0;
int linSpeed = 15;

int threshold = 160;

void linearMotion(){
	if(linearO == Up){
		motor[linear] = linSpeed;
		waitUntil(SensorValue[linI2C] >= 20);
		motor[linear] = mstop;
		linearO = Down;
		} else {
		motor[linear] = -linSpeed;
		waitUntil(SensorValue[linI2C] <= -100);
		motor[linear] = mstop;
		linearO = Up;
	}
}

bool isPushed(){
	if(SensorValue(button1) && !button1p)
	{
		button1p = true;
		return true;
		} else if(SensorValue(button2) && !button2p){
		button2p = true;
		return true;
	}

	return false;
}

void monitorLight(){
	static int minLevelIR1 = minLevel;
	static int maxLevelIR1 = 0;
	static int diffLevelIR1 = 0;

	static int minLevelIR2 = minLevel;
	static int maxLevelIR2 = 0;
	static int diffLevelIR2 = 0;

	static int minLevelIR3 = minLevel;
	static int maxLevelIR3 = 0;
	static int diffLevelIR3 = 0;

	static int minLevelIR4 = minLevel;
	static int maxLevelIR4 = 0;
	static int diffLevelIR4 = 0;

	static int minLevelIR5 = minLevel;
	static int maxLevelIR5 = 0;
	static int diffLevelIR5 = 0;

	int lightLevel1 = SensorValue[iFLeft];
	int lightLevel2 = SensorValue[iFRight];
	int lightLevel3 = SensorValue[iRight];
	int lightLevel4 = SensorValue[iBack];
	int lightLevel5 = SensorValue[iLeft];
	if ( time1[T1] > 100 )  {
		diffLevelIR1 = maxLevelIR1 - minLevelIR1;
		maxLevelIR1 = 0;
		minLevelIR1 = minLevel;

		diffLevelIR2 = maxLevelIR2 - minLevelIR2;
		maxLevelIR2 = 0;
		minLevelIR2 = minLevel;

		diffLevelIR3 = maxLevelIR3 - minLevelIR3;
		maxLevelIR3 = 0;
		minLevelIR3 = minLevel;

		diffLevelIR4 = maxLevelIR4 - minLevelIR4;
		maxLevelIR4 = 0;
		minLevelIR4 = minLevel;

		diffLevelIR5 = maxLevelIR5 - minLevelIR5;
		maxLevelIR5 = 0;
		minLevelIR5 = minLevel;
		clearTimer(T1);
		} else {
		if ( lightLevel1 < minLevelIR1 ) {
			minLevelIR1 = lightLevel1;
			} else if ( lightLevel1 > maxLevelIR1 ) {
			maxLevelIR1 = lightLevel1;
		}
		if ( lightLevel2 < minLevelIR2 ) {
			minLevelIR2 = lightLevel2;
			} else if ( lightLevel2 > maxLevelIR2 ) {
			maxLevelIR2 = lightLevel2;
		}
		if ( lightLevel3 < minLevelIR3 ) {
			minLevelIR3 = lightLevel3;
			} else if ( lightLevel3 > maxLevelIR3 ) {
			maxLevelIR3 = lightLevel3;
		}
		if ( lightLevel4 < minLevelIR4 ) {
			minLevelIR4 = lightLevel4;
			} else if ( lightLevel4 > maxLevelIR4 ) {
			maxLevelIR4 = lightLevel4;
		}
		if ( lightLevel5 < minLevelIR5 ) {
			minLevelIR5 = lightLevel5;
			} else if ( lightLevel5 > maxLevelIR5 ) {
			maxLevelIR5 = lightLevel5;
		}
	}
	vFLeft = diffLevelIR1;
	vFRight = diffLevelIR2;
	vRight = diffLevelIR3;
	vBack = diffLevelIR4;
  vLeft = diffLevelIR5;
}

bool detect(){
	if(SensorValue[sonar] <= distanceConnect){
		return true;
	}
	return false;
}

void changeDirection(){
		//while(true){}
}

task ledHz(){
	while(true){
		wait10Msec(10);
		SensorValue[ir] = 1;
		wait10Msec(10);
		SensorValue[ir] = 0;
	}
}

task main(){

	startTask(ledHz);

	direction = Forward;
	linearO = Down;
	SensorValue[linI2C] = 0;

	while(true){
		monitorLight();
		if(isPushed()){
			if(button1p == true){
				button1p = button2p = false;
			}
			else if(button2p == true){
				button1p = button2p = false;
			}
		}
	}
}
