#pragma config(Sensor, in1,    motorSteer_angle, sensorPotentiometer)
#pragma config(Sensor, dgtl1,  button1,        sensorTouch)
#pragma config(Sensor, dgtl2,  button2,        sensorTouch)
#pragma config(Motor,  port1,           motorBackRight, tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           motorSteer,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          motorBackLeft, tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

bool button1p;
bool button2p;

enum turn {Forward , Left, Right};
enum turn direction;

int speed = 25;
int steerSpeed = 20;
int motorStop = 0;

bool isPushed(){
	if(SensorValue(button1) && !button1p)
  {
    button1p = true;
    return true;
  }

  if(SensorValue(button2) && !button2p)
  {
    button2p = true;
    return true;
  }
  return false;
}

void straightOne(){
	int count = 0;
	while(count < 3){
		button1p = false;
		button2p = false;
		motor[motorBackLeft] = speed;
		motor[motorBackRight] = speed;

		count++;
		wait1Msec(1000);
	}
}

void turner(){
	if(direction == Left){
		while(SensorValue[motorSteer_angle] <= 1500){
			motor[motorSteer] = steerSpeed;
		}
		motor[motorSteer] = motorStop;

		motor[motorBackLeft] = speed/2;
		motor[motorBackRight] = speed;
		wait10Msec(500);
		motor[motorBackLeft] = motorStop;
		motor[motorBackRight] = motorStop;

		while(SensorValue[motorSteer_angle] >= 1500){
			motor[motorSteer] = -steerSpeed;
		}
		motor[motorSteer] = motorStop;
	}else if(direction == Right){
	/*
		while(SensorValue[motorSteer_angle] <= 1500){
			motor[motorSteer] = -steerSpeed;
		}
	*/
		motor[motorSteer] = -steerSpeed;
		wait10Msec(150);
		motor[motorSteer] = motorStop;

		motor[motorBackLeft] = speed;
		motor[motorBackRight] = speed/2;
		wait10Msec(500);
		motor[motorBackLeft] = motorStop;
		motor[motorBackRight] = motorStop;

		/*
		while(SensorValue[motorSteer_angle] >= 1500){
			motor[motorSteer] = steerSpeed;
		}
		*/

		motor[motorSteer] = steerSpeed;
		wait10Msec(125);
		motor[motorSteer] = motorStop;
	}
}

task main(){
	button1p = button2p = false;
	direction = Forward;

	while(true){
		if(isPushed()){
			if(button1p == true){
				straightOne();
				motor[motorBackLeft] = motorStop;
				motor[motorBackRight] = motorStop;
			}else if(button2p == true){
				direction = Right;
				turner();
				direction = Forward;
				button1p = button2p = false;
			}
		}
	}
}
